# -*- coding: utf-8 -*-
"""clase 8 de septiembre forero sanchez .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cEQTiw4RdprK_jkTYuSjR1_GaTzNirKH

<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A: ING PAOLA ANDRE QUINTERO**
#**PRESENTADO POR: Maria Jose Forero Sanchez**
#**GRADO DECIMO**
#**8 SEPTIEMBRE 2022**
"""



"""#**¿Que es python?**
#  Python es un lenguaje de scripting independiente de plataforma y orientado a objetos, preparado para realizar cualquier tipo de programa, desde aplicaciones Windows a servidores de red o incluso, páginas web. 
# Fecha de lanzamiento fue a finales de los 80 y principio de los 90 ente 1991.
#creadores:Guido van Rossum

#Recuperado de: 
https://www.redalyc.org/pdf/1815/181531232001.pdf

https://desarrolloweb.com/articulos/1325.php
"""

print("Esto es una suma")
numero_uno=8
numero_dos=478
resultado=numero_uno + numero_dos
print (resultado)

print("Esto es una resta")
numero_uno=254
numero_dos=478
resultado=numero_uno - numero_dos
print (resultado)

print("Esto es una multiplicacion")
numero_uno=7858
numero_dos=54554
resultado=numero_uno * numero_dos
print (resultado)

print("Esto es una divicion")
numero_uno=5565
numero_dos=2445
resultado=numero_uno / numero_dos
print (resultado)

"""#Ejercicios de tipos de datos simples

## Ejercicio 1
escribe un programa que pregunte el nombre del usuario en la consola y un numero entero e imprima un numero entero e imprima por pantalla en la linea distintas el nombre del usuario tnta veces como el numero introducido.
"""

nombre = input("¿como te llamas? ")
n = input("Introduce un numero entero: ")
print((nombre + "\n") * int (n))

"""## Ejercicio 2 

Escribir un programa que pida al usuario su peso (en Kg) y estatura (en metros) , calcule el indice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tu indice de masa corporal es <imc>' donde '<imc> es el indice de masa corporal calculado redondeando con dos decimales.
"""

peso = input ("¿Cual es tu peso en Kg?")
estatura = input("¿cual es tu estatura en metros?")
imc = round (float(peso)/float(estatura)**2,2)
print("Tu indice de masa corporal es " + str(imc))

"""# **Librerias en Pyhton**

# **1. Pandas**

una de las más utilizadas para el tratamiento de datos en Python. Una de las principales virtudes que tiene la librería es la carga de datos, la cual permite realizar la carga desde distintos orígenes.

2. Numpy

Numpy es una librería de Python para Machine Learning caracterizada por ser la librería de procesamiento de arrays por excelencia. Contiene una gran colección de funciones que permiten realizar cálculos matemáticos complejos sobre arrays multidimensionales. 

3. SciPy

La librería Scipy está formada por una serie de módulos que proporcionan funcionalidad para resolver el cómputo de tareas científicas y analíticas

# **4. Scikit-learn**

Una de las librerías Python más importantes enfocadas al Machine Learning es Scikit-Learn. Esta librería está formada por una gran cantidad de algoritmos de ML (clasificación, regresión, clustering, etc.) y proporciona funcionalidades básicas que facilitan el trabajo diario de los ingenieros dedicados a este tipo de tareas

# **5. Matplotlib**

Hasta este punto únicamente hemos introducido librerías que nos permiten manipular los datos y realizar algoritmos.

# **6.TensorFlow**

Tensorflow es una de las librerías open source más importantes de Deep Learning y ha sido creada por Google. Está formada por un ecosistema flexible de herramientas, librerías y recursos de la comunidad y ayuda a los investigadores a innovar aplicando técnicas de Machine Learning.
"""